version: '3'

services:
  postgres:
    image: postgres:10.3
    environment:
      - POSTGRES_DB=opendatacube
      - POSTGRES_PASSWORD=opendatacubepassword
      - POSTGRES_USER=opendatacube

  jupyter:
    build:
      context: .
    environment:
      - DB_HOSTNAME=postgres
      - DB_USERNAME=opendatacube
      - DB_PASSWORD=opendatacubepassword
      - DB_DATABASE=opendatacube
        # - AWS_ACCESS_KEY_ID=${ODC_ACCESS_KEY}
        # - AWS_SECRET_ACCESS_KEY=${ODC_SECRET_KEY}
    ports:
      - "8888:8888"
    volumes:
      - ./data:/notebooks
    shm_size: 1g
    command: jupyter notebook --ip="*" --NotebookApp.token=''

    
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.4.3
    container_name: elasticsearch
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./etc/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - "9200:9200"
  kibana:
    image: docker.elastic.co/kibana/kibana:6.4.3
    volumes:
      - ./etc/kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:
      - "5601:5601"

