echo:
	echo hi 

assess:
	# (export PAGER=cat; pydoc assess-my-data-lake)
	python3 assess-my-data-lake.py --bucket dev-usgs-landsat --prefix collection1/level2/albers/oli-tirs/2013/
	# python3 assess-my-data-lake.py --bucket dev-usgs-landsat --prefix collection1/level2/albers/oli-tirs/2018/046/028/




git:
	(cd /opt/indexc2; make)

