runi:
	python3 index_nigeria_test.py
run:
	python3 test_xml.py

git:
	(cd /opt/indexc2; make)

initdb:
	datacube system init

product:
	echo add product definition via yaml here

all:	initdb product runi
